package com.example.model

object CallerPhrases {
    private val phrases = mapOf(
        1 to "Top of the line",
        2 to "One small duck",
        3 to "Goodness me",
        4 to "Knock at the door",
        5 to "Fingers in a hand",
        6 to "Choo choo train",
        7 to "Lucky number seven",
        8 to "Garden gate",
        9 to "Doctor's time",
        10 to "A big fat hen",
        11 to "Two standing legs",
        12 to "One dozen",
        13 to "Unlucky for some",
        14 to "Valentine's day",
        15 to "Independence day",
        16 to "Sweet sixteen",
        17 to "Dancing queen",
        18 to "Voting age",
        19 to "Goodbye teens",
        20 to "One score",
        21 to "Key to the door",
        22 to "Two little ducks",
        23 to "You and me",
        24 to "Two dozen",
        25 to "Silver jubilee",
        26 to "Republic day",
        27 to "Gateway to heaven",
        28 to "Duck and its mate",
        29 to "In your prime",
        30 to "Dirty thirty",
        31 to "Baskin Robbins",
        32 to "Buckle my shoe",
        33 to "All the threes",
        34 to "Ask for more",
        35 to "Flirty thirty five",
        36 to "Three dozen",
        37 to "Mixed luck",
        38 to "Overtake",
        39 to "Watch the line",
        40 to "Naughty forty",
        41 to "Life begins at 41",
        42 to "Winnie the Pooh",
        43 to "Climb a tree",
        44 to "All the fours",
        45 to "Halfway house",
        46 to "Up to tricks",
        47 to "Four and seven",
        48 to "Four dozen",
        49 to "Rise and shine",
        50 to "Golden jubilee",
        51 to "Royal Bengal",
        52 to "Cards in a pack",
        53 to "Stuck in a tree",
        54 to "Clean the floor",
        55 to "All the fives",
        56 to "Pick up sticks",
        57 to "Heinz varieties",
        58 to "Make them wait",
        59 to "Just a shine",
        60 to "Five dozen",
        61 to "Baker's bun",
        62 to "Turn on the screw",
        63 to "Tickle me 3",
        64 to "Red raw",
        65 to "Old age pension",
        66 to "Clickty click",
        67 to "Made in heaven",
        68 to "Saving grace",
        69 to "Ulta pulta",
        70 to "Lucky blind 70",
        71 to "Bang the drum",
        72 to "Six dozen",
        73 to "Under the tree",
        74 to "Still alive",
        75 to "Diamond jubilee",
        76 to "Trombones",
        77 to "Two hockey sticks",
        78 to "Heavens gate",
        79 to "One more to 80",
        80 to "Gandhi's breakfast",
        81 to "Stop and run",
        82 to "Straight from heaven",
        83 to "Time for tea",
        84 to "Seven dozen",
        85 to "Staying alive",
        86 to "Between the sticks",
        87 to "Fat lady with a cane",
        88 to "Two fat ladies",
        89 to "Almost there",
        90 to "Top of the shop"
    )

    fun getPhrase(number: Int): String {
        val nickname = phrases[number] ?: "Number $number"
        return "$number - $nickname"
    }

    fun getNicknameOnly(number: Int): String {
        return phrases[number] ?: "Number $number"
    }
}
